class UniversityDepartments {
  static const List<String> departments = [
    'Computer Science',
    'Engineering',
    'Business Administration',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Psychology',
    'English Literature',
    'History',
    'Economics',
    'Political Science',
    'Philosophy',
    'Art & Design',
    'Music',
    'Education',
    'Medicine',
    'Nursing',
    'Law',
    'Architecture',
    'Environmental Science',
    'Sociology',
    'Geography',
    'Communications',
    'Library Science',
    'Human Resources',
    'Finance',
    'Marketing',
    'Administration',
    'Maintenance',
  ];

  static const Map<String, String> departmentIcons = {
    'Computer Science': '💻',
    'Engineering': '⚙️',
    'Business Administration': '💼',
    'Mathematics': '📊',
    'Physics': '🔬',
    'Chemistry': '🧪',
    'Biology': '🧬',
    'Psychology': '🧠',
    'English Literature': '📚',
    'History': '📜',
    'Economics': '📈',
    'Political Science': '🏛️',
    'Philosophy': '🤔',
    'Art & Design': '🎨',
    'Music': '🎵',
    'Education': '🎓',
    'Medicine': '⚕️',
    'Nursing': '👩‍⚕️',
    'Law': '⚖️',
    'Architecture': '🏗️',
    'Environmental Science': '🌱',
    'Sociology': '👥',
    'Geography': '🌍',
    'Communications': '📢',
    'Library Science': '📖',
    'Human Resources': '👤',
    'Finance': '💰',
    'Marketing': '📣',
    'Administration': '🏢',
    'Maintenance': '🔧',
  };

  static String getIcon(String department) {
    return departmentIcons[department] ?? '🏫';
  }
}
